//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int SplitPosition {
            get {
                return ((int)(this["SplitPosition"]));
            }
            set {
                this["SplitPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("597, 458")]
        public global::System.Drawing.Point Size {
            get {
                return ((global::System.Drawing.Point)(this["Size"]));
            }
            set {
                this["Size"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Helper</string>\r\n  <string>Смотреть</string>\r\n  <string>Добавить</string>\r" +
            "\n  <string>Удалить</string>\r\n  <string>Редактировать</string>\r\n  <string>Названи" +
            "е</string>\r\n  <string>Ссылку</string>\r\n  <string>Сейчас</string>\r\n  <string>Всег" +
            "о</string>\r\n  <string>Оценка</string>\r\n  <string>Ок</string>\r\n  <string>Отмена</" +
            "string>\r\n  <string>Смена названия</string>\r\n  <string>Введите новое название</st" +
            "ring>\r\n  <string>Не корректные данные</string>\r\n  <string>Смена ссылки</string>\r" +
            "\n  <string>Введите новую ссылку</string>\r\n  <string>Сохранить</string>\r\n  <strin" +
            "g>Применить</string>\r\n  <string>Отмена</string>\r\n  <string>Цвет</string>\r\n  <str" +
            "ing>Шрифт</string>\r\n  <string>Добавление нового стиля</string>\r\n  <string>Введит" +
            "е название</string>\r\n  <string>Свой стиль..</string>\r\n  <string>Другие шрифты</s" +
            "tring>\r\n  <string>Дизайн</string>\r\n  <string>Обновить</string>\r\n  <string>Скопир" +
            "овать название</string>\r\n  <string>Доп. Инфо.</string>\r\n  <string>Авто. Обнов.</" +
            "string>\r\n  <string>Элемент</string>\r\n  <string>Сайт</string>\r\n  <string>Добавлен" +
            "ие</string>\r\n  <string>Введите ссылку на нужную  страницу</string>\r\n  <string>Са" +
            "йта нет в базе данных</string>\r\n  <string>Закачка дополнительной утилиты</string" +
            ">\r\n  <string>Картинку</string>\r\n  <string>Из ссылки</string>\r\n  <string>Из файла" +
            "</string>\r\n  <string>Сохранить резервную копию?</string>\r\n  <string>Загрузить ре" +
            "зервную копию</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ButtonsName {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ButtonsName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>40</string>
  <string>all </string>
  <string>Режимы:view,allreadyview,all</string>
  <string>30</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Config {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Config"]));
            }
            set {
                this["Config"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>online.anidub.[=_=]&lt;title&gt;[=_=]&lt;/title&gt;[=_=] [[=_=] из [=_=]""image_src"" href=""[=_=]""</string>
  <string>animevost.org[=_=] / [=_=][[=_=][1-[=_=] из [=_=]""imgRadius"" src=""[=_=]""</string>
  <string>www.lostfilm.tv[=_=] ([=_=])[=_=]&lt;td class=""t_episode_num"" rowspan=""2""&gt;[=_=]&lt;[=_=]	&lt;img src=""[=_=]""</string>
  <string>vk.com/videos[=_=]&lt;title&gt;[=_=] | [=_=]class=""summary fl_l""&gt;[=_=] [=_=] style=""background-image: url('[=_=]')""</string>
  <string>amvnews.ru[=_=]&lt;title&gt;[=_=]&lt;/title&gt;[=_=]in=view&amp;amp;id=[=_=]&lt;/link&gt;[=_=]align=&amp;quot;center&amp;quot;&amp;gt;&amp;lt;img src=&amp;quot;[=_=]&amp;quot</string>
  <string>newstudio.tv[=_=]  class=""active""&gt;[=_=]&lt;/a&gt;[=_=]РЎРµСЂРёСЏ[=_=])[=_=]class=""postImg"" title=""[=_=]""</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SiteInfo {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SiteInfo"]));
            }
            set {
                this["SiteInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>//Font(Name,Size)</string>
  <string>Microsoft Sans Serif</string>
  <string>8,25</string>
  <string>//Color(Указываеться три цвета, цвет фона, цвет компонентов, цвет шрифта, указываеть в виде RGB: 192, 0, 0; 255, 255, 255)</string>
  <string>246, 245, 240</string>
  <string>239, 226, 207</string>
  <string>115, 99, 86</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Style {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Style"]));
            }
            set {
                this["Style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ReserveCopy {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ReserveCopy"]));
            }
            set {
                this["ReserveCopy"] = value;
            }
        }
    }
}
